version: 2.1

jobs:
  build:
    docker:
      - image: unityci/editor:2022.3.32f1-android-3
    environment:
      UNITY_LICENSE: $UNITY_LICENSE 
    steps:
      - checkout

      # Vérification de l'installation de Unity
      - run:
          name: Vérification de la présence de Unity
          command: ls -la /opt/unity/Editor/ || echo "Unity n'est pas installé !"

      # Vérification que l'exécutable Unity est bien accessible
      - run:
          name: Vérification de l'exécutable Unity
          command: |
            if [ ! -f "/opt/unity/Editor/Unity" ]; then
              echo "L'exécutable Unity n'existe pas !"
              exit 1
            fi

      # Donner les permissions d'exécution à Unity
      - run:
          name: Donner les permissions à Unity
          command: chmod +x /opt/unity/Editor/Unity

      # Vérification du contenu du répertoire
      - run:
          name: Vérification des fichiers du projet
          command: ls -la $(pwd)

      # Vérification que le fichier BuildScript.cs est bien présent
      - run:
          name: Vérification du script de build Unity
          command: |
            if [ ! -f "$(pwd)/Assets/Editor/BuildScript.cs" ]; then
              echo "Le fichier BuildScript.cs est introuvable !"
              exit 1
            fi

      # Configuration de la licence Unity
      - run:
          name: Configure Unity License
          command: |
            mkdir -p ~/.config/unity3d/Unity
            echo "$UNITY_LICENSE" > ~/.config/unity3d/Unity/Unity_lic.ulf
            # Vérifier que la licence a été correctement écrite
            if [ ! -f ~/.config/unity3d/Unity/Unity_lic.ulf ]; then
              echo "Erreur: La licence Unity n'a pas pu être écrite correctement !"
              exit 1
            fi

      # Lancer la build Unity
      - run:
          name: Lancer la build Unity
          command: |
            /opt/unity/Editor/Unity -batchmode -nographics -quit \
            -projectPath $(pwd) -executeMethod BuildScript.PerformBuild \
            -logFile logs/build.log || echo "Échec de la build Unity."

      # Vérification des logs Unity
      - run:
          name: Affichage des logs Unity
          command: cat logs/build.log || echo "Le fichier de log est introuvable."

      # Vérifier si la build a été créée
      - run:
          name: Vérifier si la build a été créée
          command: |
            if [ -d "$(pwd)/Builds" ]; then
              echo "La build a été créée avec succès."
            else
              echo "Le dossier Builds est vide ou n'existe pas."
              exit 1
            fi

      # Stockage des artifacts
      - store_artifacts:
          path: $(pwd)/Builds
          destination: build_output

workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: develop
