version: 2.1

orbs:
  unity: game-ci/unity@1.7.1

jobs:
  install_sdk:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: Install Android SDK
          command: |
            # Installer le SDK Android
            apt-get update
            apt-get install -y wget unzip openjdk-11-jdk
            wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O android_sdk.zip
            unzip android_sdk.zip -d /usr/local/android-sdk
            rm android_sdk.zip
            # Définir les variables d'environnement
            export ANDROID_HOME=/usr/local/android-sdk
            export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
            # Accepter les licences et installer les composants nécessaires
            yes | sdkmanager --licenses
            sdkmanager "platforms;android-33" "build-tools;33.0.0" "platform-tools"

workflows:
  version: 2
  build-unity-project:
    jobs:
      - install_sdk
      - unity/build:
          name: 'build-android'
          step-name: 'Build Android'
          unity-serial-var-name: 'UNITY_SERIAL'
          unity-username-var-name: 'UNITY_USERNAME'
          unity-password-var-name: 'UNITY_PASSWORD'
          executor:
            name: 'unity/ubuntu'
            target_platform: 'android'
            editor_version: '2022.3.3f1'
            resource_class: 'large'
          project-path: .
          build-target: 'Android'
          context: DreamVillageUnityInfo
          requires:
            - install_sdk
