version: 2.1

jobs:
  build:
    docker:
      - image: unityci/editor:2022.3.32f1-android-3
    steps:
      - checkout

      - restore_cache:
          keys:
            - unity-docker-cache-v1-{{ checksum "Dockerfile" }}
            - unity-docker-cache-v1
      
      # Donner les permissions d'exécution à Unity
      - run:
          name: Donner les permissions à Unity
          command: chmod +x /opt/unity/Editor/Unity

      # Configuration de la licence Unity
      - run:
          name: Configurer la licence Unity
          command: |
            mkdir -p $HOME/.local/share/unity3d/Unity/
            echo $UNITY_LICENSE | base64 --decode > $HOME/.local/share/unity3d/Unity/Unity_lic.ulf
            cat $HOME/.local/share/unity3d/Unity/Unity_lic.ulf | head -c 50  # Vérifie si le fichier est bien écrit
            chmod 777 $HOME/.local/share/unity3d/Unity/Unity_lic.ulf
      
      - run:
          name: Vérifier le fichier de licence
          command: cat $HOME/.local/share/unity3d/Unity/Unity_lic.ulf || echo "❌ Licence introuvable !"
            
      - run:
          name: Activer la licence Unity
          command: |
            /opt/unity/Editor/Unity -batchmode -nographics -quit \
            -manualLicenseFile $HOME/.local/share/unity3d/Unity/Unity_lic.ulf

      - run:
          name: Vérifier les permissions du fichier de licence
          command: ls -la $HOME/.local/share/unity3d/Unity/

      # Lancer la build Unity
      - run:
          name: Lancer la build Unity
          command: |
            /opt/unity/Editor/Unity -batchmode -nographics -quit \
            -projectPath $(pwd) -executeMethod BuildScript.PerformBuild \
            -logFile logs/build.log || echo "Échec de la build Unity."

      # Vérification des logs Unity
      - run:
          name: Affichage des logs Unity
          command: cat logs/build.log || echo "Le fichier de log est introuvable."

      # Vérifier si la build a été créée
      - run:
          name: Vérifier si la build a été créée
          command: |
            if [ -d "$(pwd)/Builds" ]; then
              echo "La build a été créée avec succès."
            else
              echo "Le dossier Builds est vide ou n'existe pas."
              exit 1
            fi

      # Stockage des artifacts
      - store_artifacts:
          path: $(pwd)/Builds
          destination: build_output

      # Sauvegarder l'image dans le cache
      - save_cache:
          paths:
            - /opt/unity
          key: unity-docker-cache-v1-{{ checksum "Dockerfile" }}

workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: develop
