version: 2.1

jobs:
  test-env-vars:
    docker:
      - image: cimg/base:stable  # Une image légère pour exécuter le test
    steps:
      - run:
          name: Vérification de la variable UNITY_ENCODED_LICENSE
          command: |
            if [ -z "$UNITY_ENCODED_LICENSE" ]; then
              echo "❌ La variable UNITY_ENCODED_LICENSE n'est pas définie ou est vide."
              exit 1
            else
              echo "✅ La variable UNITY_ENCODED_LICENSE est bien définie."
            fi

workflows:
  build-unity-project:
    jobs:
      - test-env-vars
