version: 2.1

executors:
  unity-executor:
    docker:
      - image: unityci/editor:ubuntu-2022.3.32f1-android-3
    resource_class: large

jobs:
  build:
    executor: unity-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - unity-cache-{{ checksum "Packages/manifest.json" }}
            - unity-cache-v1

      # Build Projet
      - run:
          name: Build project
          command: |
            # Activer la licence Unity
            unity-editor \
              -batchmode \
              -nographics \
              -silent-crashes \
              -logFile /dev/stdout \
              -username "$UNITY_USERNAME" \
              -password "$UNITY_PASSWORD" \
              -serial "$UNITY_SERIAL" \
              -projectPath $(pwd) \
              -buildTarget Android \
              -quit
            
            # Lancer la build
            unity-editor \
              -batchmode \
              -nographics \
              -silent-crashes \
              -logFile /dev/stdout \
              -projectPath $(pwd) \
              -buildTarget Android \
              -customBuildTarget Android \
              -customBuildPath /project/build/Android/Android.apk \
              -quit

      - save_cache:
          paths:
            - /root/.cache/unity3d
            - /root/.local/share/unity3d
            - /project/Library
          key: unity-cache-{{ checksum "Packages/manifest.json" }}

      # Upload artifact
      - run:
          name: Archive Build
          command: |
            mkdir -p /tmp/build
            cp -r build/Android/Android.apk /tmp/build/
            
      - store_artifacts:
          path: /tmp/build
          destination: Build

      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "build.gradle" }}
            - gradle-cache-v1

      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: gradle-cache-{{ checksum "build.gradle" }}

workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: develop
