version: 2.1

orbs:
  unity: game-ci/unity@1.7.1

workflows:
  build-unity-project:
    jobs:
      - unity/build:
          name: 'build-android'
          step-name: 'Build Android'
          unity-license-var-name: 'UNITY_ENCODED_LICENSE'
          executor:
            name: 'unity/ubuntu'
            target_platform: 'android'
            editor_version: '2022.3.3f1'
            resource_class: 'large'
          project-path: .
          build-target: 'Android'
          context: unity
