version: 2.1

orbs:
  unity: game-ci/unity@editor-ubuntu-2022.3.32f1-android-3.1.0

workflows:
  create-unity-activation-file:
    jobs:
      - unity/create-activation-file:
          editor_version: 2022.3.32f1
