executors:
  unity-executor:
    docker:
      - image: unityci/editor:ubuntu-2022.3.32f1-android-3
    resource_class: large

jobs:
  build:
    executor: unity-executor
    context: DreamVillageUnityInfo
    steps:
      - checkout

      # Build Projet
      - run:
          name: Build project
          command: |
            # Activer la licence Unity
            unity-editor \
              -batchmode \
              -nographics \
              -silent-crashes \
              -logFile /dev/stdout \
              -username "$UNITY_EMAIL" \
              -password "$UNITY_PASSWORD" \
              -serial "$UNITY_SERIAL" \
              -projectPath $(pwd) \
              -buildTarget Android \
              -quit
            
            # Lancer la build
            unity-editor \
              -batchmode \
              -nographics \
              -silent-crashes \
              -logFile /dev/stdout \
              -projectPath $(pwd) \
              -buildTarget Android \
              -quit

      # Upload artifact
      - run:
          name: Archive Build
          command: |
            mkdir -p /tmp/build
            cp -r build/Android/Android.apk /tmp/build/
      - store_artifacts:
          path: /tmp/build
          destination: Build

workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          context: DreamVillageUnityInfo
          filters:
            branches:
              only: develop
