version: 2.1

executors:
  unity-executor:
    docker:
      - image: unityci/editor:ubuntu-2022.3.32f1-android-3
    resource_class: large

jobs:
  build:
    executor: unity-executor
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true
          image: unityci/editor:ubuntu-2022.3.32f1-android-3 
          registry: "docker.io"  
          force_pull: false 

      - restore_cache:
          keys:
            - unity-cache-{{ checksum "Packages/manifest.json" }}
            - unity-cache-v1

      # Build Projet
      - run:
          name: Build project
          command: |
            
            mkdir -p /project/build/Android
          
            # Activer la licence Unity
            unity-editor \
              -batchmode \
              -nographics \
              -silent-crashes \
              -logFile /dev/stdout \
              -username "$UNITY_USERNAME" \
              -password "$UNITY_PASSWORD" \
              -serial "$UNITY_SERIAL" \
              -projectPath $(pwd) \
              -buildTarget Android \
              -quit
            
            # Lancer la build
            unity-editor \
              -batchmode \
              -nographics \
              -silent-crashes \
              -logFile /tmp/unity_build.log \
              -projectPath $(pwd) \
              -buildTarget Android \
              -customBuildTarget Android \
              -customBuildPath /project/build/Android/Android.apk \
              -quit

            echo "Unity Build Logs:"
            cat /tmp/unity_build.log

      - save_cache:
          paths:
            - /root/.cache/unity3d
            - /root/.local/share/unity3d
            - /project/Library
          key: unity-cache-{{ checksum "Packages/manifest.json" }}

      # Upload artifact
      - run:
          name: Archive Build
          command: |
            mkdir -p /tmp/build
            cp -r /project/build/Android/Android.apk /tmp/build/
            
      - store_artifacts:
          path: /tmp/build
          destination: Build

workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: develop
