version: 2.1

jobs:
  build:
    docker:
      - image: unityci/editor:2022.3.32f1-android-3

    steps:
      - checkout
      
      - run:
          name: Build Unity vers Android
          command: |
            /opt/unity/Editor/Unity -batchmode -nographics -quit \
            -projectPath $(pwd) -executeMethod BuildScript.PerformBuild \
            -logFile logs/build.log

      - run:
          name: Donner les permissions à `gradlew`
          command: chmod +x YourExportedAndroidProject/gradlew

      - run:
          name: Build APK
          command: |
            cd YourExportedAndroidProject
            ./gradlew assembleDebug

      - store_artifacts:
          path: YourExportedAndroidProject/app/build/outputs/apk/debug/app-debug.apk
          destination: apk

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
