version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-26-node  # Image Docker pour Android
    environment:
      GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx2g"'
    steps:
      - checkout  # Récupère le code depuis le repo
          
      - run:
          name: Build Unity vers Android
          command: |
            /opt/unity/Editor/Unity -batchmode -nographics -quit \
            -projectPath $(pwd) -executeMethod BuildScript.PerformBuild \
            -logFile logs/build.log

      - run:
          name: Vérifier si `build.gradle` existe
          command: ls -R YourExportedAndroidProject/

      - run:
          name: Donner les permissions à `gradlew`
          command: chmod +x YourExportedAndroidProject/gradlew

      - run:
          name: Build APK
          command: |
            cd YourExportedAndroidProject
            ./gradlew assembleDebug

      - store_artifacts:
          path: YourExportedAndroidProject/app/build/outputs/apk/debug/app-debug.apk
          destination: apk

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop 
