version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2023.01  # Image Docker pour Android
    environment:
      GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx2g"'
    steps:
      - checkout  # Récupère le code depuis le repo
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Installer les dépendances
          command: ./gradlew dependencies
      - run:
          name: Build APK Debug
          command: ./gradlew assembleDebug
      - save_cache:
          key: gradle-cache-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle
      - store_artifacts:
          path: app/build/outputs/apk/debug/app-debug.apk
          destination: apk

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop 
